# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'video' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for video
  pod 'AFNetworking', '~> 2.5'
  pod 'TZImagePickerController'
  pod 'Masonry'
  pod 'GPUImage'
  pod 'OpenCV', '~> 3.0.0'
  target 'videoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'videoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
